### ISSUE TITLE
👤User Story #3: Make the Initial Commit

### ISSUE THREAD

**Issue by kpetrauskas92** [kpetrauskas92/Mont-Adventures-PP5#10]
**Description:**

As a developer, I want to make the initial commit to populate the repository with a basic project skeleton.

**Tasks**

- [x] Create the initial basic file structure for the project (backend, frontend folders, etc.).
- [x] Make the initial commit with the basic project skeleton.
- [x] Push the changes to the GitHub repository.

**Acceptance Criteria**

> The project has a well-organized file structure.
> The initial commit is made and pushed to GitHub.

**Comment by kpetrauskas92** [comment]
All tasks completed.
