### ISSUE TITLE
👤User Story #6: Create the Frontend Project Skeleton

### ISSUE THREAD

**Issue by kpetrauskas92** [kpetrauskas92/Mont-Adventures-PP5#13]
**Description:**

As a developer, I want to create a frontend project skeleton so that i have a structured starting point for frontend development.

**Tasks:**

- [x]  Initialize frontend using a framework of choice.
- [x]  Set up a directory for frontend code (CSS, JS).
- [x]  Configure basic project settings like package dependencies.

**Acceptance Criteria:**

> Frontend is initialized.
> Basic project settings and dependencies are configured.

**Comment by kpetrauskas92** [comment]
All tasks completed.
