### ISSUE TITLE
👤User Story #8: Create AWS S3 Buckets

### ISSUE THREAD

**Issue by kpetrauskas92** [kpetrauskas92/Mont-Adventures-PP5#15]
**Description:**

As a developer, I want to create AWS S3 buckets so that we have a dedicated place to store static and media files.

**Tasks:**

- [x] Sign in to the AWS Management Console or create a new account.
- [x] Navigate to the S3 service and create new buckets for static and media files.
- [x] Configure bucket permissions and policies.

**Acceptance Criteria:**

> AWS S3 buckets for static and media files are created.
> Appropriate permissions and policies are set.

**Comment by kpetrauskas92** [comment]
All tasks completed.
