### ISSUE TITLE
👤User Story #9: Configure Django to Use AWS S3

### ISSUE THREAD

**Issue by kpetrauskas92** [kpetrauskas92/Mont-Adventures-PP5#16]
**Description:**

As a developer, I want to configure Django to use AWS S3 so that static and media files are served from S3.

**Tasks:**

- [x] Install necessary packages like boto3 and django-storages.
- [x] Update Django settings to use S3 for static and media files.
- [x] Run tests to ensure that static files are properly served.

**Acceptance Criteria:**

> Necessary packages for S3 integration are installed.
> Django settings are configured to use AWS S3.
> Static files are being served from S3.

**Comment by kpetrauskas92** [comment]
Run tests when running test deployment.

**Comment by kpetrauskas92** [comment]
All tests and task completed.
