### ISSUE TITLE
👤User Story #10: Integrate Django Allauth

### ISSUE THREAD

**Issue by kpetrauskas92** [kpetrauskas92/Mont-Adventures-PP5#17]
**Description:**

As a developer, I want to integrate Django Allauth into the project so that we can leverage its authentication capabilities.

**Tasks:**

- [x] Install the Django Allauth package.
- [x] Add Django Allauth to the project settings.
- [x] Run migrations to update the database schema.

**Acceptance Criteria:**

> Django Allauth is installed and configured.
> Database is updated with necessary tables for authentication.

**Comment by kpetrauskas92** [comment]
All tasks completed.
