### ISSUE TITLE
👤User Story #12: Implement User Login

### ISSUE THREAD

**Issue by kpetrauskas92** [kpetrauskas92/Mont-Adventures-PP5#19]
**Description:**

As a user, I want to be able to log in so that I can access my account and use the application.

**Tasks:**

- [x] Configure Django Allauth for user login.
- [x] Create login forms and views.
- [x] Implement frontend login page.

**Acceptance Criteria:**

> User login is functional.
> Users can log in from the frontend login page.

**Comment by kpetrauskas92** [comment]
All tasks completed.
