### ISSUE TITLE
User Story #1: Initialize the Project Repository

### ISSUE THREAD

**Issue by kpetrauskas92** [kpetrauskas92/Mont-Adventures-PP5#2]
**Description:**

As a developer, I want to initialize a new project repository so that we have a centralized location for code storage and version control.

**Tasks**

- [ ] Create a new repository on GitHub.
- [ ] Add a README file to describe the project.
- [ ] Add a .gitignore file to exclude unnecessary files from version control.

**Acceptance Criteria**

>A new repository exists on GitHub.
> README and .gitignore are present.
