### ISSUE TITLE
👤User Story #13: Set Up Email Verification

### ISSUE THREAD

**Issue by kpetrauskas92** [kpetrauskas92/Mont-Adventures-PP5#20]
**Description:**

As a user, I want to verify my email address so that my account is more secure.

**Tasks:**

- [x] Configure Django Allauth for email verification.
- [x] Implement email sending functionality.
- [x] Create email templates.

**Acceptance Criteria:**

> Email verification is functional.
> Users receive a verification email upon registration.

**Comment by kpetrauskas92** [comment]
All tasks completed.
Email template will be moved to finishing sprints.
