### ISSUE TITLE
👤User Story #14: Implement Password Reset Functionality

### ISSUE THREAD

**Issue by kpetrauskas92** [kpetrauskas92/Mont-Adventures-PP5#21]
**Description:**

As a user, I want to reset my password in case I forget it, so that I can recover access to my account.

**Tasks:**

- [x] Configure Django Allauth for password resets.
- [x] Implement password reset forms and views.
- [x] Create password reset email templates.

**Acceptance Criteria:**

> Password reset functionality is in place.
> Users can initiate a password reset and receive an email for it.

**Comment by kpetrauskas92** [comment]
All tasks completed, email template will be moved to finishing sprints.
