### ISSUE TITLE
👤User Story #16: Deploy a Test Version to Heroku

### ISSUE THREAD

**Issue by kpetrauskas92** [kpetrauskas92/Mont-Adventures-PP5#23]
**Description:**

As a developer, I want to deploy a test version of the application to Heroku to validate that it runs as expected in a cloud environment.

**Tasks:**

- [x] Create a new Heroku app via the Heroku dashboard or CLI.
- [x] Connect the Heroku app to the project repository.
- [x] Deploy the application to Heroku.

**Acceptance Criteria:**

> A new Heroku app is created.
> The Heroku app is connected to the project repository.
> The application is successfully deployed to Heroku.

**Comment by kpetrauskas92** [comment]
All tasks completed.
