### ISSUE TITLE
👤User Story #3: Create Frontend Interface for Trip Packages

### ISSUE THREAD

**Issue by kpetrauskas92** [kpetrauskas92/Mont-Adventures-PP5#27]
**Description:**

As a user, I want to easily find and view packages that interest me through a frontend interface complete with a filtering system.

**Tasks:**

- [x] Create frontend components for listing trip packages.
- [x] Implement a filtering system for the trip package list.
- [x] Create frontend components for viewing trip package details.

**Acceptance Criteria:**

> Frontend components for listing and filtering trip packages are functional.
> Frontend components for viewing trip package details are functional.

**Comment by kpetrauskas92** [comment]
All tasks completed.
