### ISSUE TITLE
👤User Story #1: Initialize the Project Repository

### ISSUE THREAD

**Issue by kpetrauskas92** [kpetrauskas92/Mont-Adventures-PP5#8]
**Description:**

As a developer, I want to initialize a new project repository so that we have a centralized location for code storage and version control.

**Tasks**

- [x] Create a new repository on GitHub.
- [x] Add a README file to describe the project.
- [x] Add a .gitignore file to exclude unnecessary files from version control.

**Acceptance Criteria**

>A new repository exists on GitHub.
> README and .gitignore are present.

**Comment by kpetrauskas92** [comment]
All tasks completed.
